version: '3.3'

services:
  air_pollute:
    image: ragou/pollute_air_pollute
    volumes:
      - ./:/code
    networks:
      - pollute_net

  flaski:
    build:
      context: .
      dockerfile: Dockerfile.v
    depends_on: 
      - air_pollute
    ports: 
      - "5000:5000"
    volumes:
      - ./templates:/app/templates
    networks:
      - pollute_net

networks:
  pollute_net:
    driver: bridge

# volumes:
#   - ./: